apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: chatbot-test-app-16
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/mvaldron-rhdh/chatbot-test-app-16:36e192a5b39110cd1ddadf4d71096979d4482f68@sha256:fcdae93c62956c4ff968c90900fbaf85bb50aaf5ef05a3998e4bf4b411edc533 # use pre-built to bootstrap 
          name: app-inference
